name: testssl
version: '2.9.5-5snap1'
summary: Testing TLS/SSL encryption anywhere on any port
description: |
  testssl.sh is a free command line tool which checks a server's service on any
  port for the support of TLS/SSL ciphers, protocols as well as some
  cryptographic flaws.

  Key features:

    - Clear output: you can tell easily whether anything is good or bad
    - Ease of installation: It works for Linux, OSX/Darwin, FreeBSD, NetBSD,
      OpenBSD (needs bash) and MSYS2/Cygwin out of the box: no need to install
      or to configure something. No gems, CPAN, pip or the like/
    - Flexibility: You can test any SSL/TLS enabled and STARTTLS service, not
      only webservers at port 443
    - Toolbox: Several command line options help you to run YOUR test and
      configure YOUR output
    - Reliability: features are tested thoroughly
    - Verbosity: If a particular check cannot be performed because of a missing
      capability on your client side, you'll get a warning
    - Privacy: It's only you who sees the result, not a third party
    - Freedom: It's 100% open source. You can look at the code, see what's going
      on and you can change it.


grade: stable
confinement: strict

apps:
  testssl:
    command: testssl.sh
    plugs: [network]

parts:
  testssl:
    plugin: dump
    source: https://github.com/drwetter/testssl.sh/archive/v2.9.5-5.tar.gz
    stage-packages:
      - dnsutils
      - bsdmainutils
